// This file is generated by Slice Machine. Update with care!

export { default as Footer } from './Footer'
export { default as NavItem } from './NavItem'
export { default as Slider } from './Slider'
