// This file is generated by Slice Machine. Update with care!

import Footer from './Footer';
import ImageText from './ImageText';
import Images from './Images';
import Info from './Info';
import NavItem from './NavItem';
import Slider from './Slider';
import Socials from './Socials';

export {
	Footer,
	ImageText,
	Images,
	Info,
	NavItem,
	Slider,
	Socials,
};

export const components = {
	footer: Footer,
	image_text: ImageText,
	images: Images,
	info: Info,
	nav_item: NavItem,
	slider: Slider,
	socials: Socials,
};
